### ISSUE TITLE
Menu links are not working

### ISSUE THREAD

**Issue by vikramjb** [xenon92/resurrectionremix-website#13]
Noted something on the site, clicking on the menu links should take us tot he appropriate section. It does not seem to be doing it. 

Is it the same for everyone ?

**Comment by FallenKN** [comment]
Everything is working

**Comment by 7dir** [comment]
Not working

**Comment by xenon92** [comment]
Fixed. Sorry, it took a bit long, didn't get time to look into it.

Commit - https://github.com/xenon92/resurrectionremix-website/commit/ab93f5067066189c6614080b10dab7b06bc28226
