### ISSUE TITLE
Update Lollipop to Marshmallow

### ISSUE THREAD

**Issue by api-walker** [xenon92/resurrectionremix-website#5]
The official website mentions Lollipop, but no Marshmallow. Should it updated to marshmallow?

**Comment by MezaCorleehone** [comment]
Hello good afternoon.
Sorry if I violate the rules for doing this.

but in many roms of different developers.
It shows the same fault.

when I connect my adapter HML, my note 2 N7100 freezes.
Having to remove the battery.

and then cyclically becomes without connecting the HML

Ditto N3 and N4 only supports HML
Rom stock 4.4.2 also supports it.

my note 2 is not defective chip

I will be forced to return stock rom 4.4.2

until some rom that error is corrected.

Sorry for the inconvenience ...

**Comment by MezaCorleehone** [comment]
I want to reach the comentatio developers.
but only answer assistants.

eh installed their ROMs, 5.1.1 and 6.0.1
but do not support HML
and tends to freeze my note.
after a while of use.
it slows down until it freezes.

having to remove the battery.

their roms are very fast and I like.
I prefer them more than the others eh installed.

that is the only rom. which it has properly configured video performance.
and my emulators run very well.

ANNOTATION:
My note is not defective Exynos chip. Chip (0xF7) (12.2012)

I thought the problem of sudden death.
but I'm in 4.4.4 Ditto N4 and all is well
does not freeze and supports HML

**Comment by xenon92** [comment]
Hi @api-walker,

I am closing this issue as I am following up with the issue #7 for updating the website to Marshmallow. If you want, you can contribute with screenshots in that issue.

Hi @MezaCorleehone ,

Please post your issue in the respective thread of your ROM on XDA from where you downloaded the ROM. The developer/community will help you out. This issue log and repository is only Resurrection Remix ROM website.

Regards,
xenon92
