### ISSUE TITLE
PLEASE UPDATE THE WEBSITE TO Marshmallow

### ISSUE THREAD

**Issue by YUDHPK** [xenon92/resurrectionremix-website#7]
So that newcomers get proper information.
also update all the pics . 
if you want i can provide you with all the media part.
I can even help in commits.
you can contact me on xda by the name YUDH or on google+ with the name (Praful Kothari)
@xenon92

**Comment by xenon92** [comment]
Hi @YUDHPK, 

I'll update the website, if you provide me with screenshots from the Marshmallow ROM.

Please create the screenshots like they are currently on the website.

1. Shadow only at the bottom
2. Black / Dark frame (we have light background on the website) - The device frame should be the same on all the images
3. All screenshots with the device frame should be of the same size (resolution)
4. Make screenshots of things that are similar to the ones on the website (easier for description).
	- Configuration
	- Quick Settings
	- Updates
	- Process in notification panel
	- Floating Window
	- Gestures
5. Other screenshots that I'll update in "More Screenshots" on the website.

Regards,
xenon92

**Comment by xenon92** [comment]
Website up-to-date for android Nougat.
