### ISSUE TITLE
Big issue with usage access since 2-3-Versions...

### ISSUE THREAD

**Issue by Anagastes** [xenon92/resurrectionremix-website#8]
Hello, sorry for bad english.

Since 2 3 versions I have all possible Apps with the "of utilisation data access", however, not those who also wish really access. The mistake is also with the topical version. My Apps have only accessed by a "Dirty-Flash" has made. Otherwise I cannot permit the access.

I use the topical Opengapps. (Use your lollipop on OnePlus 1)

**Comment by xenon92** [comment]
Hi Anagastes, 

Please use the respective Resurrection Remix ROM thread on XDA for troubleshooting and your queries. This repository and issue log is only for the Resurrection Remix website.

Regards,
xenon92
